"""empty message

Revision ID: bac26865c6b2
Revises: b0c281678d84
Create Date: 2020-12-09 13:47:26.564998

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bac26865c6b2"
down_revision = "b0c281678d84"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("property_address_id_fkey", "property", type_="foreignkey")
    op.create_foreign_key(
        None, "property", "property_address", ["address_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "property", type_="foreignkey")
    op.create_foreign_key(
        "property_address_id_fkey", "property", "property_address", ["address_id"], ["id"]
    )
    # ### end Alembic commands ###
